version: '3'

services:
  broker-mqtt:
    image: broker-mqtt
    build: .
    container_name: broker-mqtt
    logging:            # Configuração de log
      options:
        max-size: "50m" # Tamanho máximo de cada arquivo de log
        max-file: "2"   # Número máximo de arquivos de log
    restart: unless-stopped
    ports:
      - "8000:8000"
      - "8080:8080"
      - "1883:1883"
    environment:
      - LOG_CONFIG_PROD=true
    networks:
       - broker

networks:
  broker:
    driver: bridge
